insta/urls.py
from django.contrib import admin
from django.urls import path, include
from main import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include('main.urls')),

]

main/urls.py
from django.urls import path
from . import views

app_name = "insta"

urlpatterns = [
    path("logout.html/", views.logout_request, name="logout"),
    path("login.html/", views.login_request, name="login"),
    path("register.html/", views.register, name='register'),
    path("posts.html", views.create_post, name="create"),
    path("", views.homepage, name="homepage"),
    path('<int:username>/', views.get_user_profile, name="profile"),
    path("home.html/", views.Feed.as_view(), name="feed"),
    path('delete/<post_id>', views.delete_post, name='delete')
]

main/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile', null=True)

    class Meta:
        app_label = "insta"

    def __str__(self):
        return self.user.username


class Post(models.Model):
    user = models.ForeignKey(User, default=None, on_delete=models.CASCADE, null=True, unique=False)
    text = models.TextField(default="", blank=True, max_length=100, null=True)
    pub_date = models.DateTimeField('date published', default=timezone.now)

    class Meta:
        app_label = "insta"

    def __str__(self):
        return self.text

main/forms.py
from django.forms import ModelForm
from .models import Post


class Post(ModelForm):
    class Meta:
        model = Post
        fields = ('text', )

main/views.py
from pyexpat.errors import messages
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect
from .models import Profile, Post
from django.views import generic
from django.utils import timezone
from .forms import Post as PostForm


def logout_request(request):
    logout(request)
    return redirect("insta:homepage")


def login_request(request):
    if request.method == 'GET':
        form = AuthenticationForm()
        return render(request, 'login.html', {'form': form})

    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            username = User.objects.get(username=request.user)
            return HttpResponseRedirect('/%s/' % username.id)
        else:
            form = AuthenticationForm(request.POST)
            return render(request, 'login.html', {'form': form})
    else:
        form = AuthenticationForm()
        return render(request, 'login.html', {'form': form})


def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=password)
            login(request, user)
            return redirect("insta:login")
        else:
            return render(request, 'register.html', {'form': form})
    else:
        form = UserCreationForm()
        return render(request, 'register.html', {'form': form})


def homepage(request):
    return redirect('insta:login')


def get_user_profile(request, username):
    user = get_object_or_404(User, pk=username)
    prof = Profile.objects.get_or_create(user=user)
    return render(request, "profile.html", {"profile": prof})


class Feed(generic.ListView):
    template_name = 'base.html'
    context_object_name = 'posts'

    def get_queryset(self):
        return Post.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')


def create_post(request):
    form = PostForm
    if request.method == 'POST':
        postf = PostForm(request.POST)
        if postf.is_valid():
            profile = postf.save(commit=False)
            profile.user = request.user
            profile.save()
            return redirect('insta:feed')
    return render(request, 'posts.html', {'form': form})


def delete_post(request, post_id):
    post = get_object_or_404(Post, pk=post_id, user=request.user)
    post.delete()
    return redirect("insta:feed")

main/templates/base.html
{% extends 'home.html' %}

{% block title %}
    <title>Mini-Instagram</title>
{% endblock %}

{% block content %}
    {% if user.is_authenticated %}
        {% if posts %}
            <ul class="posts">
            {% for post in posts %}
                    {% if post.text %}
                        <h4>
                            <a href="{% url 'insta:delete' post.id %}">Delete</a>
                            {{ post.user }}
                            {{ post.text }}
                            {{ post.pub_date }}
                        </h4>
                    {% endif %}
            {% endfor %}
            </ul>
        {% else %}
            <p class="no-posts">No posts.</p>
    {% endif %}
    {% else %} 
        <meta http-equiv="REFRESH" content="0;url=./login">
    {% endif %}
{% endblock %}

main/templates/home.html
<!DOCTYPE html>
<html lang="">
    <body>
        {% block content %}
        {% endblock %}
        <footer>
            <ul class="navbar">
                <li><a href="/home.html">Feed</a></li>
                <li>•</li>
                <li><a href="/posts.html">Create a Post</a></li>
                <li>•</li>
                <li> <a href="/{{ user.id }}">My Profile</a></li>
                <li>•</li>
                <li><a href="/login.html">Logout</a></li>
            </ul>
        </footer>
    </body>
</html>

main/templates/login.html
{% block head %}
  <title>Login</title>
{% endblock %}

{% block body %}
  {% if form.errors %}
    <p>Your username and password didn't match. Please try again.</p>
  {% endif %}

  <form method="post">
    {% csrf_token %}
    <table>
      <tr>
        <td>{{ form.username.label_tag }}</td>
        <td>{{ form.username }}</td>
      </tr>
      <tr>
        <td>{{ form.password.label_tag }}</td>
        <td>{{ form.password }}</td>
      </tr>
    </table>

    <input type="submit" value="login" />
    <input type="hidden" name="next" value="{{ next }}" />
      <br><br>
      Don't have an account? <a href="/register.html" target="blank"><strong>register here</strong></a>!

  </form>
{% endblock %}

main/templates/posts.html
{% extends 'home.html' %}
{% if user.is_authenticated %}
    <p>user</p>
    {% block title %}
    {% endblock %}

    {% block content %}
        <h1>Create a Post</h1>

        <form method="POST">
            {% csrf_token %}
            <table>
                {{ form.as_table }}
                <tr>
                    <td></td>
                    <td><input type="submit" name="submit" value="Post" /></td>
                </tr>
             </table>
        </form>
    </div>    
    
    {% endblock %}
{% else %}
    <meta http-equiv="REFRESH" content="0;url=./login.html">
{% endif %}

main/templates/profile.html
{% extends 'home.html' %}

{% block title %}
    <title>Mini-Instagram </title>
{% endblock %}

{% block content %}
    <div class="profile">
        <h2>{{ profile }}</h2>
        <p>{{ profile.name }}</p>
    </div>
{% endblock %}

main/templates/register.html
{% block title %}
    <title>Register</title>
{% endblock %}

{% block content %}
    <div class="main-container">
        <h1>Register</h1>
        <form method="POST">
            {% csrf_token %}
           <table>
                {{ form.as_table }}
                 <tr>
                    <td></td>
                    <td><input type="submit" name="submit" value="Register" /></td>
                </tr>
             </table>
        </form>
        <div class="inner-container">
            <p>Already have an account? <a href="/login.html"><strong>Login</strong></a> here.</p>
        </div>
    </div>
{% endblock %}